export const QUOTES_LIST_START = 'QUOTES_LIST_START';
export const QUOTES_LIST_SUCCESS = 'QUOTES_LIST_SUCCESS';
export const QUOTES_LIST_ERROR = 'QUOTES_LIST_ERROR';

export const FILTER_SEARCH = 'FILTER_SEARCH';
export const FILTER_SEARCH_NULL = 'FILTER_SEARCH_NULL';

export const QUOTES_TICK_START = 'QUOTES_TICK_START';
export const QUOTES_TICK_SUCCES = 'QUOTES_TICK_SUCCES';
export const QUOTES_TICK_ERROR = 'QUOTES_TICK_ERROR';
